sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dancingdumpling/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -r CI=true dancingdumpling/react-test npm run test 

after_success:
  - docker build -t dancingdumpling/multi-client ./client
  - docker build -t dancingdumpling/multi-nginx ./nginx
  - docker build -t dancingdumpling/multi-server ./server
  - docker build -t dancingdumpling/multi-worker ./worker