sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dancingdumpling/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dancingdumpling/react-test npm run test 

after_success:
  - docker build -t dancingdumpling/multi-client ./client
  - docker build -t dancingdumpling/multi-nginx ./nginx
  - docker build -t dancingdumpling/multi-server ./server
  - docker build -t dancingdumpling/multi-worker ./worker
  # LOG INTO THE DOCKER CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #TAKE IMAGES AND OUSH THEM TO DOCKER HUB 
  - docker push dancingdumpling/multi-client
  - docker push dancingdumpling/multi-nginx
  - docker push dancingdumpling/multi-server
  - docker push dancingdumpling/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-496472651608"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
