version: '3'
services:
  client: 
    image: "dancingdumpling/multi-client"
    mem_limit: 128m
  api:
    image: "dancingdumpling/multi-server"
    mem_limit: 128m
    environment:
    # get it from aws elastiCache redis link and it defined in elastic beanstalk - configuration - software - environment properties
      - REDIS_HOST=$REDIS_HOST 
      - REDIS_PORT=$REDIS_PORT 
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "dancingdumpling/multi-worker"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "dancingdumpling/multi-nginx"
    mem_limit: 128m
    ports:
      - "80:80"